title: MAJID JANGANI
description: Predicting Market Extremes Using Machine Learning
show_downloads: true
theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
plugins:
  - jekyll-remote-theme
permalink: /:title/
baseurl: "/Time-Series-Regression-For-Market-Extremes"
